### ISSUE TITLE
Start Round times incorrect

### ISSUE THREAD

**Issue by tvand7093** [BMVW-Capstone/Mobile-Rounds#101]
### Environment
- System Time: 8:06 AM
- Times displayed in application
  - 2:00
  - 8:00

### Expected

Shouldn't it show the 8:00 round time and 12:00?

**Comment by ChrisWillette** [comment]
the current changes in e688931e874b2101466dd558f22331d9fdfd1bc8 look like they ~~should do the trick~~ might display three times at exactly 2am

**Comment by wyattmcgehee** [comment]
Fixed by #130 ?
