### ISSUE TITLE
Rename different terms in app to fit their terminology.

### ISSUE THREAD

**Issue by tvand7093** [BMVW-Capstone/Mobile-Rounds#113]
We need to replace the different words in the application with those that they find more appropriate. This does not include the renaming of code, however if there is time, we should do this for future developers to understand the terminology. Renaming the API endpoints will be pretty easy, and makes sense no matter the amount of time we have.

**Comment by tvand7093** [comment]
@mb19, could you please update this issue with the correct list of terms from the picture you took in the last meeting?

**Comment by mb19** [comment]
Area

System

- Device
  - Unit
  - Parameter (value)
    - Spec
      - Criteria > Value
