### ISSUE TITLE
Indicator for completed entries

### ISSUE THREAD

**Issue by mb19** [BMVW-Capstone/Mobile-Rounds#121]
We need to append some sort of indicator to each list item for a completed entry. One idea is a checkbox next to each completed item and station.

**Comment by ChrisWillette** [comment]
I started going down a completely ghetto road. was going to do some janky business where i render check boxes without being user-interactive, but that's not happening. CheckBox controls are awkward looking, and if I'm interpreting the MSDN docs correctly, this type of solution will involve some custom .xaml template thingies. I'm just not about that.

there's every possibility that I simply do not know the proper terminology to search for. Marking a list/stack item as updated/completed with an X or check mark isn't exactly rare behavior. 

I think the next step will have to be programmatically setting a border/text color that updates. that, from what i've seen, is something that actually should be doable (read as: straightforward).

**Comment by tvand7093** [comment]
Fixed by #147
