### ISSUE TITLE
documention

### ISSUE THREAD

**Issue by ChrisWillette** [BMVW-Capstone/Mobile-Rounds#35]
We need to update the readme and other docs to reflect the change from windows 10 to 8.

**Comment by ChrisWillette** [comment]
Throw in a spellcheck of the readme, as well.

**Comment by tvand7093** [comment]
As far as I am aware, we are sticking to windows 10 going forwards (according to Terry). We also should throw in some documentation on what solutions/projects do what things.

**Comment by tvand7093** [comment]
Also, see #37 for a good starting template for a README file per subsystem. I think we should have the main README link to nested subsystem README's where appropriate. Perhaps a table outlining the different systems in the application.

**Comment by tvand7093** [comment]
Once we are happy with all the diagrams in VS, we should probably run through and convert them to PDF's. Even if they are not 100% matching the code, it would be beneficial to have them as docs so that anyone can view them, and not just people with the Enterprise VS edition.
