### ISSUE TITLE
Sync data from the API server

### ISSUE THREAD

**Issue by tvand7093** [BMVW-Capstone/Mobile-Rounds#54]
This is just a general task. The basic client for doing web requests (that are authenticated already) is already setup. From any ViewModel, all 
```csharp
var api = Platform.ServiceResolver.Resolve<Platform.IApiRequest>();
var regions = api.GetAsync<List<Models.RegionModel>>("https://localhost:1234/api/regions");
```

This will get you an object that can do web requests with. The example above shows getting a list of regions. Note that the port `1234` should be replaced with the actual server port (too lazy to look right now). 

Currently, the following API's work (run the server to see the full list of endpoints):
- Regions
- Stations
- Unit of Measurements

**Comment by ChrisWillette** [comment]
I'd like to pull this into my testing of the local file handling. i'll get a quick rundown from somebody in person to make sure i'm using the feature correctly. mostly, i'd like to see where the app stores these pull-downs locally and then refactor the voodoo async file handlers if needed.
